// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stock/stock_manager.proto

package stock_manager

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StockPriceRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockPriceRequest) Reset()         { *m = StockPriceRequest{} }
func (m *StockPriceRequest) String() string { return proto.CompactTextString(m) }
func (*StockPriceRequest) ProtoMessage()    {}
func (*StockPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stock_manager_268a579709e922f2, []int{0}
}
func (m *StockPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPriceRequest.Unmarshal(m, b)
}
func (m *StockPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPriceRequest.Marshal(b, m, deterministic)
}
func (dst *StockPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPriceRequest.Merge(dst, src)
}
func (m *StockPriceRequest) XXX_Size() int {
	return xxx_messageInfo_StockPriceRequest.Size(m)
}
func (m *StockPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StockPriceRequest proto.InternalMessageInfo

func (m *StockPriceRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type StockPriceResponse struct {
	Symbol               string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Prices               []*StockPrice `protobuf:"bytes,2,rep,name=prices,proto3" json:"prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StockPriceResponse) Reset()         { *m = StockPriceResponse{} }
func (m *StockPriceResponse) String() string { return proto.CompactTextString(m) }
func (*StockPriceResponse) ProtoMessage()    {}
func (*StockPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stock_manager_268a579709e922f2, []int{1}
}
func (m *StockPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPriceResponse.Unmarshal(m, b)
}
func (m *StockPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPriceResponse.Marshal(b, m, deterministic)
}
func (dst *StockPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPriceResponse.Merge(dst, src)
}
func (m *StockPriceResponse) XXX_Size() int {
	return xxx_messageInfo_StockPriceResponse.Size(m)
}
func (m *StockPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockPriceResponse proto.InternalMessageInfo

func (m *StockPriceResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *StockPriceResponse) GetPrices() []*StockPrice {
	if m != nil {
		return m.Prices
	}
	return nil
}

type StockPrice struct {
	Open                 float64  `protobuf:"fixed64,1,opt,name=Open,proto3" json:"Open,omitempty"`
	High                 float64  `protobuf:"fixed64,2,opt,name=High,proto3" json:"High,omitempty"`
	Low                  float64  `protobuf:"fixed64,3,opt,name=Low,proto3" json:"Low,omitempty"`
	Close                float64  `protobuf:"fixed64,4,opt,name=Close,proto3" json:"Close,omitempty"`
	Volume               uint64   `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockPrice) Reset()         { *m = StockPrice{} }
func (m *StockPrice) String() string { return proto.CompactTextString(m) }
func (*StockPrice) ProtoMessage()    {}
func (*StockPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_stock_manager_268a579709e922f2, []int{2}
}
func (m *StockPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPrice.Unmarshal(m, b)
}
func (m *StockPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPrice.Marshal(b, m, deterministic)
}
func (dst *StockPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPrice.Merge(dst, src)
}
func (m *StockPrice) XXX_Size() int {
	return xxx_messageInfo_StockPrice.Size(m)
}
func (m *StockPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPrice.DiscardUnknown(m)
}

var xxx_messageInfo_StockPrice proto.InternalMessageInfo

func (m *StockPrice) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *StockPrice) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *StockPrice) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *StockPrice) GetClose() float64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *StockPrice) GetVolume() uint64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *StockPrice) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*StockPriceRequest)(nil), "StockPriceRequest")
	proto.RegisterType((*StockPriceResponse)(nil), "StockPriceResponse")
	proto.RegisterType((*StockPrice)(nil), "StockPrice")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StockManagerClient is the client API for StockManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StockManagerClient interface {
	GetStockPrices(ctx context.Context, in *StockPriceRequest, opts ...grpc.CallOption) (*StockPriceResponse, error)
}

type stockManagerClient struct {
	cc *grpc.ClientConn
}

func NewStockManagerClient(cc *grpc.ClientConn) StockManagerClient {
	return &stockManagerClient{cc}
}

func (c *stockManagerClient) GetStockPrices(ctx context.Context, in *StockPriceRequest, opts ...grpc.CallOption) (*StockPriceResponse, error) {
	out := new(StockPriceResponse)
	err := c.cc.Invoke(ctx, "/StockManager/GetStockPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockManagerServer is the server API for StockManager service.
type StockManagerServer interface {
	GetStockPrices(context.Context, *StockPriceRequest) (*StockPriceResponse, error)
}

func RegisterStockManagerServer(s *grpc.Server, srv StockManagerServer) {
	s.RegisterService(&_StockManager_serviceDesc, srv)
}

func _StockManager_GetStockPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockManagerServer).GetStockPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StockManager/GetStockPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockManagerServer).GetStockPrices(ctx, req.(*StockPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StockManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StockManager",
	HandlerType: (*StockManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockPrices",
			Handler:    _StockManager_GetStockPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock/stock_manager.proto",
}

func init() {
	proto.RegisterFile("stock/stock_manager.proto", fileDescriptor_stock_manager_268a579709e922f2)
}

var fileDescriptor_stock_manager_268a579709e922f2 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xc9, 0x9f, 0x06, 0x9c, 0x8a, 0xe8, 0x2a, 0xba, 0x2d, 0x82, 0x21, 0x5e, 0x02, 0x42,
	0x82, 0xf5, 0x11, 0x3c, 0xe8, 0x41, 0x51, 0xe3, 0xcd, 0x4b, 0x49, 0xcb, 0x10, 0xa3, 0xc9, 0x4e,
	0xcc, 0x6e, 0x2b, 0x5e, 0x3d, 0x79, 0xf7, 0xd1, 0x7c, 0x05, 0x1f, 0x44, 0x76, 0x12, 0x68, 0xa1,
	0x78, 0x09, 0xdf, 0xfc, 0xe6, 0x0f, 0x5f, 0xbe, 0x85, 0x91, 0x36, 0x34, 0x7f, 0x4d, 0xf9, 0x3b,
	0xad, 0x73, 0x95, 0x17, 0xd8, 0x26, 0x4d, 0x4b, 0x86, 0xc6, 0xc7, 0x05, 0x51, 0x51, 0x61, 0x9a,
	0x37, 0x65, 0x9a, 0x2b, 0x45, 0x26, 0x37, 0x25, 0x29, 0xdd, 0x75, 0xa3, 0x33, 0xd8, 0x7b, 0xb4,
	0x4b, 0xf7, 0x6d, 0x39, 0xc7, 0x0c, 0xdf, 0x16, 0xa8, 0x8d, 0x38, 0x84, 0x40, 0x7f, 0xd4, 0x33,
	0xaa, 0xa4, 0x13, 0x3a, 0xf1, 0x56, 0xd6, 0x57, 0xd1, 0x03, 0x88, 0xf5, 0x61, 0xdd, 0x90, 0xd2,
	0xf8, 0xdf, 0xb4, 0x38, 0x85, 0xa0, 0xb1, 0x83, 0x5a, 0xba, 0xa1, 0x17, 0x0f, 0x27, 0xc3, 0x64,
	0x6d, 0xb9, 0x6f, 0x45, 0x5f, 0x0e, 0xc0, 0x0a, 0x0b, 0x01, 0xfe, 0x5d, 0x83, 0x8a, 0x2f, 0x39,
	0x19, 0x6b, 0xcb, 0xae, 0xcb, 0xe2, 0x59, 0xba, 0x1d, 0xb3, 0x5a, 0xec, 0x82, 0x77, 0x43, 0xef,
	0xd2, 0x63, 0x64, 0xa5, 0x38, 0x80, 0xc1, 0x65, 0x45, 0x1a, 0xa5, 0xcf, 0xac, 0x2b, 0xac, 0xb7,
	0x25, 0x55, 0x8b, 0x1a, 0xe5, 0x20, 0x74, 0x62, 0x3f, 0xeb, 0x2b, 0x7b, 0xd3, 0x94, 0x35, 0xca,
	0x80, 0x29, 0xeb, 0xc9, 0x0b, 0x6c, 0xb3, 0x93, 0xdb, 0x2e, 0x3e, 0xf1, 0x04, 0x3b, 0x57, 0x68,
	0x56, 0xe6, 0xb4, 0x10, 0xc9, 0x46, 0x56, 0xe3, 0xfd, 0x64, 0x33, 0x92, 0xe8, 0xe4, 0xf3, 0xe7,
	0xf7, 0xdb, 0x1d, 0x89, 0x23, 0x4e, 0x7d, 0x79, 0x9e, 0x16, 0x68, 0xa6, 0xdd, 0xe3, 0xf0, 0x7f,
	0xcf, 0x02, 0x4e, 0xff, 0xe2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xb9, 0x3d, 0xa2, 0xb8, 0x01,
	0x00, 0x00,
}
